/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadComicIdRouteImport } from './routes/read.$comicId'
import { Route as StudioComicIdRouteImport } from './routes/studio.$comicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadComicIdRoute = ReadComicIdRouteImport.update({
  id: '/read/$comicId',
  path: '/read/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioComicIdRoute = StudioComicIdRouteImport.update({
  id: '/studio/$comicId',
  path: '/studio/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/read/$comicId': typeof ReadComicIdRoute
  '/studio/$comicId': typeof StudioComicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/read/$comicId': typeof ReadComicIdRoute
  '/studio/$comicId': typeof StudioComicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/read/$comicId': typeof ReadComicIdRoute
  '/studio/$comicId': typeof StudioComicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/read/$comicId' | '/studio/$comicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/read/$comicId' | '/studio/$comicId'
  id: '__root__' | '/' | '/read/$comicId' | '/studio/$comicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadComicIdRoute: typeof ReadComicIdRoute
  StudioComicIdRoute: typeof StudioComicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$comicId': {
      id: '/read/$comicId'
      path: '/read/$comicId'
      fullPath: '/read/$comicId'
      preLoaderRoute: typeof ReadComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$comicId': {
      id: '/studio/$comicId'
      path: '/studio/$comicId'
      fullPath: '/studio/$comicId'
      preLoaderRoute: typeof StudioComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadComicIdRoute: ReadComicIdRoute,
  StudioComicIdRoute: StudioComicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
